/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as FormImport } from './routes/form'
import { Route as IndexImport } from './routes/index'
import { Route as FormFormSlugImport } from './routes/form_.$formSlug'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const FormRoute = FormImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FormFormSlugRoute = FormFormSlugImport.update({
  id: '/form_/$formSlug',
  path: '/form/$formSlug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/form_/$formSlug': {
      id: '/form_/$formSlug'
      path: '/form/$formSlug'
      fullPath: '/form/$formSlug'
      preLoaderRoute: typeof FormFormSlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form': typeof FormRoute
  '/login': typeof LoginRoute
  '/form/$formSlug': typeof FormFormSlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form': typeof FormRoute
  '/login': typeof LoginRoute
  '/form/$formSlug': typeof FormFormSlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/form': typeof FormRoute
  '/login': typeof LoginRoute
  '/form_/$formSlug': typeof FormFormSlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/form' | '/login' | '/form/$formSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/form' | '/login' | '/form/$formSlug'
  id: '__root__' | '/' | '/form' | '/login' | '/form_/$formSlug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormRoute: typeof FormRoute
  LoginRoute: typeof LoginRoute
  FormFormSlugRoute: typeof FormFormSlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormRoute: FormRoute,
  LoginRoute: LoginRoute,
  FormFormSlugRoute: FormFormSlugRoute,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/form",
        "/login",
        "/form_/$formSlug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/form": {
      "filePath": "form.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/form_/$formSlug": {
      "filePath": "form_.$formSlug.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
